As a part of this branch and pull request, create a file titled action-a/action.yml. You can do so using this quicklink or manually.
dd the following content to the action.yml file:
ame: "Hello Actions"

description: "Greet someone"

author: "octocat@github.com"



inputs:

  MY_NAME:

    description: "Who to greet"

    required: true

    default: "World"



runs:

  using: "docker"

  image: "Dockerfile"



branding:

  icon: "mic"

  color: "purple"

